export const diseaseToSpecialty = {
    "migraine": "Neurologist",
    "epilepsy": "Neurologist",
    "stroke": "Neurologist",
    "parkinson's disease": "Neurologist",
    "multiple sclerosis": "Neurologist",
    "depression": "Psychiatrist",
    "anxiety": "Psychiatrist",
    "insomnia": "Psychiatrist",
    "bipolar disorder": "Psychiatrist",
    "ptsd": "Psychiatrist",
    "heart disease": "Cardiologist",
    "hypertension": "Cardiologist",
    "arrhythmia": "Cardiologist",
    "heart failure": "Cardiologist",
    "high blood pressure": "Cardiologist",
    "skin rash": "Dermatologist",
    "acne": "Dermatologist",
    "eczema": "Dermatologist",
    "psoriasis": "Dermatologist",
    "fungal infection": "Dermatologist",
    "diabetes": "Endocrinologist",
    "thyroid": "Endocrinologist",
    "hormonal imbalance": "Endocrinologist",
    "pcos": "Endocrinologist",
    "fever": "General Physician",
    "cold": "General Physician",
    "flu": "General Physician",
    "sore throat": "General Physician",
    "body ache": "General Physician",
    "nausea": "General Physician",
    "ear pain": "ENT Specialist",
    "ear infection": "ENT Specialist",
    "sinusitis": "ENT Specialist",
    "throat pain": "ENT Specialist",
    "nosebleed": "ENT Specialist",
    "eye strain": "Ophthalmologist",
    "glaucoma": "Ophthalmologist",
    "dry eyes": "Ophthalmologist",
    "cataract": "Ophthalmologist",
    "conjunctivitis": "Ophthalmologist",
    "back pain": "Orthopedic Surgeon",
    "joint pain": "Orthopedic Surgeon",
    "arthritis": "Orthopedic Surgeon",
    "fractures": "Orthopedic Surgeon",
    "osteoporosis": "Orthopedic Surgeon",
    "pcos": "Gynecologist",
    "menstrual cramps": "Gynecologist",
    "pregnancy": "Gynecologist",
    "vaginal infection": "Gynecologist",
    "pelvic pain": "Gynecologist",
    "irregular periods": "Gynecologist",
    "child fever": "Pediatrician",
    "chickenpox": "Pediatrician",
    "measles": "Pediatrician",
    "cough in children": "Pediatrician",
    "common cold in babies": "Pediatrician",
    "vomiting in child": "Pediatrician"
  };
  